name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - ready_for_review
      - locked
      - unlocked
      - review_requested
      - review_request_removed
      
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@8b306ad1983d0ea68c43e27101123e891ecff104 # tag=v0.15.2
        env:
          GITHUB_TOKEN: "${{ secrets.BOT_TOKEN }}"
          UPDATE_RETRY_SLEEP: 60000
          UPDATE_RETRIES: 10
